apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil
spec:
  project: default
  source:
    repoURL: https://github.com/sleleu/iot-dev-sleleu.git
    targetRevision: HEAD
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: dev