apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
spec:
  source:
    repoURL: https://github.com/Sleleu/Inception-of-Things.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev