Vagrant.configure("2") do |config|

    config.vm.box = "base"
    config.vm.provider :libvirt do |lv|
      lv.memory = "4096"
      lv.cpus = "4"
    end
  
    config.vm.define "sleleuS" do |server|
      server.vm.box = "debian/bookworm64"
      server.vm.hostname = "sleleuS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provision "shell", path: "scripts/server.sh"
    end
end  